name: culto_domestico_app
description: "Registro dos cultos domésticos da família e da lista de oração."
publish_to: 'none'

version: 2.1.0+5

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/

  fonts:
    - family: PlusJakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans.ttf
