import 'package:meta/meta.dart';

enum Livro {
  genesis,
  exodo,
  levitico,
  numeros,
  deuteronomio,
  josue,
  juizes,
  rute,
  samuel,
  samuel2,
  reis,
  reis2,
  cronicas,
  cronicas2,
  esdras,
  nemias,
  ester,
  jo,
  salmos,
  proverbios,
  eclesiastes,
  cantares,
  isaias,
  jeremias,
  lamentacoes,
  ezequiel,
  daniel,
  oseias,
  joel,
  amos,
  obadias,
  jonas,
  miqueias,
  naum,
  habacuque,
  sofonias,
  ageu,
  zacarias,
  malaquias,
  mateus,
  marcos,
  lucas,
  joao,
  atos,
  romanos,
  corintios,
  corintios2,
  galatas,
  efesios,
  filipenses,
  colossenses,
  tessalonicenses,
  tessalonicenses2,
  timoteo,
  timoteo2,
  tito,
  filemom,
  hebreus,
  tiago,
  pedro,
  pedro2,
  joao1,
  joao2,
  joao3,
  judas,
  apocalipse,
}

extension DetalhesLivros on Livro {
  String get nome => const {
        Livro.genesis: "Gênesis",
        Livro.exodo: "Êxodo",
        Livro.levitico: "Levítico",
        Livro.numeros: "Números",
        Livro.deuteronomio: "Deuteronômio",
        Livro.josue: "Josué",
        Livro.juizes: "Juízes",
        Livro.rute: "Rute",
        Livro.samuel: "I Samuel",
        Livro.samuel2: "II Samuel",
        Livro.reis: "I Reis",
        Livro.reis2: "II Reis",
        Livro.cronicas: "I Crônicas",
        Livro.cronicas2: "II Crônicas",
        Livro.esdras: "Esdras",
        Livro.nemias: "Neemias",
        Livro.ester: "Ester",
        Livro.jo: "Jó",
        Livro.salmos: "Salmos",
        Livro.proverbios: "Provérbios",
        Livro.eclesiastes: "Eclesiastes",
        Livro.cantares: "Cantares",
        Livro.isaias: "Isaías",
        Livro.jeremias: "Jeremias",
        Livro.lamentacoes: "Lamentações",
        Livro.ezequiel: "Ezequiel",
        Livro.daniel: "Daniel",
        Livro.oseias: "Oseias",
        Livro.joel: "Joel",
        Livro.amos: "Amós",
        Livro.obadias: "Obadias",
        Livro.jonas: "Jonas",
        Livro.miqueias: "Miqueias",
        Livro.naum: "Naum",
        Livro.habacuque: "Habacuque",
        Livro.sofonias: "Sofonias",
        Livro.ageu: "Ageu",
        Livro.zacarias: "Zacarias",
        Livro.malaquias: "Malaquias",
        Livro.mateus: "Mateus",
        Livro.marcos: "Marcos",
        Livro.lucas: "Lucas",
        Livro.joao: "João",
        Livro.atos: "Atos",
        Livro.romanos: "Romanos",
        Livro.corintios: "I Coríntios",
        Livro.corintios2: "II Coríntios",
        Livro.galatas: "Gálatas",
        Livro.efesios: "Efésios",
        Livro.filipenses: "Filipenses",
        Livro.colossenses: "Colessenses",
        Livro.tessalonicenses: "I Tessalonicenses",
        Livro.tessalonicenses2: "II Tessalonicenses",
        Livro.timoteo: "I Timóteo",
        Livro.timoteo2: "II Timóteo",
        Livro.tito: "Tito",
        Livro.filemom: "Filemom",
        Livro.hebreus: "Hebreus",
        Livro.tiago: "Tiago",
        Livro.pedro: "I Pedro",
        Livro.pedro2: "II Pedro",
        Livro.joao1: "I João",
        Livro.joao2: "II João",
        Livro.joao3: "III João",
        Livro.judas: "Judas",
        Livro.apocalipse: "Apocalipse",
      }[this];

  int get numCapitulos => const {
        Livro.genesis: 50,
        Livro.exodo: 40,
        Livro.levitico: 27,
        Livro.numeros: 36,
        Livro.deuteronomio: 34,
        Livro.josue: 24,
        Livro.juizes: 21,
        Livro.rute: 4,
        Livro.samuel: 31,
        Livro.samuel2: 24,
        Livro.reis: 22,
        Livro.reis2: 25,
        Livro.cronicas: 29,
        Livro.cronicas2: 36,
        Livro.esdras: 10,
        Livro.nemias: 13,
        Livro.ester: 10,
        Livro.jo: 42,
        Livro.salmos: 150,
        Livro.proverbios: 31,
        Livro.eclesiastes: 12,
        Livro.cantares: 8,
        Livro.isaias: 66,
        Livro.jeremias: 52,
        Livro.lamentacoes: 5,
        Livro.ezequiel: 48,
        Livro.daniel: 12,
        Livro.oseias: 14,
        Livro.joel: 3,
        Livro.amos: 9,
        Livro.obadias: 1,
        Livro.jonas: 4,
        Livro.miqueias: 7,
        Livro.naum: 3,
        Livro.habacuque: 3,
        Livro.sofonias: 3,
        Livro.ageu: 2,
        Livro.zacarias: 14,
        Livro.malaquias: 4,
        Livro.mateus: 28,
        Livro.marcos: 16,
        Livro.lucas: 24,
        Livro.joao: 21,
        Livro.atos: 28,
        Livro.romanos: 16,
        Livro.corintios: 16,
        Livro.corintios2: 13,
        Livro.galatas: 6,
        Livro.efesios: 6,
        Livro.filipenses: 4,
        Livro.colossenses: 4,
        Livro.tessalonicenses: 5,
        Livro.tessalonicenses2: 3,
        Livro.timoteo: 6,
        Livro.timoteo2: 4,
        Livro.tito: 3,
        Livro.filemom: 1,
        Livro.hebreus: 13,
        Livro.tiago: 5,
        Livro.pedro: 5,
        Livro.pedro2: 3,
        Livro.joao1: 5,
        Livro.joao2: 1,
        Livro.joao3: 1,
        Livro.judas: 1,
        Livro.apocalipse: 22,
      }[this];

  List<int> get numVersiculos => const {
        Livro.genesis: [1],
        Livro.exodo: [2, 2],
        Livro.levitico: [2, 2],
        Livro.numeros: [2, 2],
        Livro.deuteronomio: [2, 2],
        Livro.josue: [2, 2],
        Livro.juizes: [2, 2],
        Livro.rute: [2, 2],
        Livro.samuel: [2, 2],
        Livro.samuel2: [2, 2],
        Livro.reis: [2, 2],
        Livro.reis2: [2, 2],
        Livro.cronicas: [2, 2],
        Livro.cronicas2: [2, 2],
        Livro.esdras: [2, 2],
        Livro.nemias: [2, 2],
        Livro.ester: [2, 2],
        Livro.jo: [2, 2],
      }[this];
}

class PassagemBiblica {
  final Livro livro;
  final List<int> capitulos;
  final List<int> versiculos;

  PassagemBiblica(
      {@required this.livro,
      @required this.capitulos,
      @required this.versiculos});

  @override
  String toString() {
    if (this == null) {
      return "";
    }
    final livro = this.livro.nome;
    var capitulos = "${this.capitulos[0].toString()}";
    if (this.capitulos.length == 2) {
      capitulos += " - ${this.capitulos[1].toString()}";
    }
    var versiculos = "${this.versiculos[0].toString()}";
    if (this.versiculos.length == 2) {
      versiculos += " - ${this.versiculos[1].toString()}";
    }

    return "$livro. $capitulos : $versiculos";
  }

  PassagemBiblica.fromJson(Map<String, dynamic> json)
      : livro = Livro.values[json['livro'] as int],
        capitulos = json['capitulos'].cast<int>(),
        versiculos = json['versiculos'].cast<int>();

  Map<String, dynamic> toJson() => {
        'livro': livro.index,
        'capitulos': capitulos,
        'versiculos': versiculos,
      };
}
